decoration {
    rounding = 10
    
    # Opacity
    active_opacity = 1.0
    inactive_opacity = 0.9
    fullscreen_opacity = 1.0

    # Blur settings
    blur {
        enabled = true
        size = 6
        passes = 3
        new_optimizations = true
        ignore_opacity = true
        xray = false
        brightness = 1.0
        contrast = 1.0
        vibrancy = 0.2
    }
}
